services:
  reflection-error:
    image: springboot-reflection-poc:feature-reflection-param-error
    ports:
      - "8081:8080"
    container_name: reflection-error

  reflection-success:
    image: springboot-reflection-poc:feature-reflection-param-success
    ports:
      - "8082:8080"
    container_name: reflection-success
